<?php

namespace App\Domain\Installment\CustomInstallment\Services;

use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;
use App\Domain\Installment\CustomInstallment\Entities\CustomCommentInstallment;
use App\Domain\Installment\Entities\CommentInstallment;
use App\Domain\Installment\Services\CommentInstallmentService;

class CustomCommentInstallmentService extends BaseService
{
    public function getEntity(): Entity
    {
        return CustomCommentInstallment::new();
    }

    public function create(array $object_data)
    {
        return parent::create($object_data); // TODO: Change the autogenerated stub
    }

}
