<?php

namespace App\Domain\Installment\Builders;

use App\Domain\Core\Main\Builders\BuilderEntity;

class CommentInstallmentBuilder extends BuilderEntity
{
    protected function getSearch(): string
    {
        return "comment";
    }

    public function filterBy($filter)
    {
        if (isset($filter['taken_credit_id'])) {
            $this->where('taken_credit_id', '=', $filter['taken_credit_id']);
        }
        return parent::filterBy($filter); // TODO: Change the autogenerated stub
    }
}
