<?php

namespace App\Domain\Installment\Builders;

use App\Domain\Core\Main\Builders\BuilderEntity;

class TimeScheduleTransactionBuilder extends BuilderEntity
{
    protected function getSearch(): string
    {
        return "detail";
    }

    public function filterBy($filter)
    {
        $this->orderByDesc("created_at");
        if (isset($filter['taken_credit_id'])) {
            $this->where("taken_credit_id", $filter['taken_credit_id']);
        }
        return parent::filterBy($filter); // TODO: Change the autogenerated stub
    }
}
