<?php

namespace App\Domain\Common\Api;

use App\Domain\Common\Discounts\Entities\Discount;

class DiscountProductApi extends Discount
{
    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
