<?php

namespace App\Domain\Delivery\Services;

use App\Domain\Core\Main\Entities\Entity;
use App\Domain\Core\Main\Services\BaseService;
use App\Domain\Delivery\Entities\AvailableCities;

class AvailableCitiesService extends BaseService
{

    public function getEntity(): Entity
    {
        return AvailableCities::new();
    }

    public function update($object, array $object_data)
    {
        $object_data['cityName'] = [
            'ru' => $object_data['cityNameRu'],
            'uz' => $object_data['cityNameUz']
        ];
        return parent::update($object, $object_data); // TODO: Change the autogenerated stub
    }

}
